include("${VCPKG_ROOT_DIR}/triplets/x64-windows.cmake")

if(PORT STREQUAL "gmsh")
    list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DENABLE_MESH=ON")
    list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DENABLE_EIGEN=ON")
endif()
