"""PULMTLN ParaView Macro
=======================

Loads and visualizes all ParaView results generated by a PULMTLN simulation.

Usage:
    In ParaView, go to Macros > Add New Macro, select this file, then run it
    from the Macros menu. When prompted, select the PULMTLN results folder
    (the one that contains the 'ParaView' subdirectory, e.g. 'Results/five_wires/').

    Alternatively, this script can be run directly with pvpython:
        pvpython pulmtln_paraview_macro.py [folder]

Fields visualized (one dataset per conductor excitation):
    Phi -- Electric scalar potential
    E   -- Electric field vector (HCurl)
    D   -- Electric flux density vector (HDiv)

Each conductor produces two datasets:
    <ConductorName>                -- with dielectrics (used for C matrix)
    <ConductorName>_no_dielectrics -- without dielectrics (used for L matrix)
"""

import os
import glob
import sys

try:
    import paraview.simple as pv
except ImportError:
    raise RuntimeError(
        "This script must be run inside ParaView or with pvpython."
    )


def _get_folder_from_dialog():
    """Open a native folder-selection dialog and return the chosen path."""
    folder = None

    # PySide2 ships with ParaView >= 5.9
    try:
        from PySide2.QtWidgets import QFileDialog  # type: ignore
        folder = QFileDialog.getExistingDirectory(
            None,
            "Select PULMTLN Results Folder (containing 'ParaView' subdirectory)",
        )
        return folder or None
    except Exception:
        pass

    # Older ParaView may bundle PyQt5 instead
    try:
        from PyQt5.QtWidgets import QFileDialog  # type: ignore
        folder = QFileDialog.getExistingDirectory(
            None,
            "Select PULMTLN Results Folder",
        )
        return folder or None
    except Exception:
        pass

    # Last resort: tkinter (not always available inside ParaView)
    try:
        import tkinter as tk
        from tkinter import filedialog
        root = tk.Tk()
        root.withdraw()
        folder = filedialog.askdirectory(
            title="Select PULMTLN Results Folder",
        )
        root.destroy()
        return folder or None
    except Exception:
        pass

    return None


def _resolve_paraview_dir(folder):
    """Return the directory that actually contains the .pvd files.

    Accepts either the top-level results folder (which has a 'ParaView'
    subdirectory) or the 'ParaView' subdirectory itself.
    """
    candidate = os.path.join(folder, "ParaView")
    if os.path.isdir(candidate):
        return candidate
    if os.path.isdir(folder):
        return folder
    return None


def _find_pvd_files(paraview_dir):
    """Return a sorted list of .pvd files inside *paraview_dir*."""
    return sorted(glob.glob(os.path.join(paraview_dir, "*.pvd")))


def _apply_phi_coloring(display, render_view):
    """Color *display* by the Phi scalar field and show a color bar."""
    pv.ColorBy(display, ("POINTS", "Phi"))
    display.RescaleTransferFunctionToDataRange(True, False)
    display.SetScalarBarVisibility(render_view, True)


def visualize_pulmtln_results(folder):
    """Load every .pvd result in *folder* and render it in ParaView.

    Parameters
    ----------
    folder : str
        Path to the PULMTLN results folder.  The function accepts either
        the top-level export folder (which contains a ``ParaView/``
        subdirectory) or the ``ParaView/`` subdirectory itself.

    Returns
    -------
    list of (name, reader, display) tuples, one per loaded .pvd file.
    """
    paraview_dir = _resolve_paraview_dir(folder)
    if paraview_dir is None:
        print(f"[pulmtln] ERROR: '{folder}' is not a valid directory.")
        return []

    pvd_files = _find_pvd_files(paraview_dir)
    if not pvd_files:
        print(
            f"[pulmtln] No .pvd files found in '{paraview_dir}'.\n"
            "Make sure 'exportParaViewSolution' is set to true in the "
            "PULMTLN input JSON and the simulation has been run."
        )
        return []

    print(f"[pulmtln] Found {len(pvd_files)} result file(s) in '{paraview_dir}':")
    for f in pvd_files:
        print(f"  {os.path.basename(f)}")

    # Prevent ParaView from auto-resetting the camera after every Show()
    pv._DisableFirstRenderCameraReset()

    render_view = pv.GetActiveViewOrCreate("RenderView")
    render_view.ResetCamera()

    loaded = []
    for pvd_file in pvd_files:
        name = os.path.splitext(os.path.basename(pvd_file))[0]

        reader = pv.PVDReader(registrationName=name, FileName=pvd_file)

        display = pv.Show(reader, render_view)
        display.Representation = "Surface"
        _apply_phi_coloring(display, render_view)

        loaded.append((name, reader, display))
        print(f"[pulmtln] Loaded '{name}'")

    render_view.ResetCamera()
    pv.Render()

    print(
        f"\n[pulmtln] Visualization complete — {len(loaded)} dataset(s) loaded.\n"
        "Tip: use the Pipeline Browser to toggle individual results on/off.\n"
        "Available fields: Phi (electric potential), "
        "E (electric field), D (electric flux density)."
    )

    return loaded


# ---------------------------------------------------------------------------
# Entry point — works both as a ParaView macro and as a pvpython script
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # When invoked with pvpython, an optional folder argument may be passed.
    if len(sys.argv) > 1:
        _folder = sys.argv[1]
    else:
        _folder = _get_folder_from_dialog()

    if _folder:
        print(f"[pulmtln] Loading results from: {_folder}")
        visualize_pulmtln_results(_folder)
    else:
        print("[pulmtln] No folder selected — macro cancelled.")
else:
    # Running as a ParaView macro (Macros menu)
    _folder = _get_folder_from_dialog()
    if _folder:
        print(f"[pulmtln] Loading results from: {_folder}")
        visualize_pulmtln_results(_folder)
    else:
        print("[pulmtln] No folder selected — macro cancelled.")
