name: "Ubuntu | Tulip build and tests"

permissions:
  actions: write

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
    
  workflow_dispatch:

env:
  TULIP_TOP_DIR: tulip
  MFEM_TOP_DIR: mfem

jobs:
  builds-and-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [opt]
        
    name: ${{ matrix.os }}-${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout TULIP
      uses: actions/checkout@v3
      with:
        path: ${{ env.TULIP_TOP_DIR }}
        ssh-key: ${{secrets.PULMTLN_SSH_KEY}}
        submodules: 'recursive'

    - name: getcmake
      uses: lukka/get-cmake@latest

    - name: Install system packages
      run: bash ${{ env.TULIP_TOP_DIR }}/scripts/install-packages.sh

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: eed289f6e06a5e7a5c9e6a729671b0a56af7dd69
        vcpkgJsonGlob: 'tulip/vcpkg.json'

    - name: Configure TULIP
      env:
        MFEM_PACKAGE: ${{ github.workspace }}/${{ env.MFEM_TOP_DIR }}/build
      run: |
        cmake --preset "gnu" -S ${{ env.TULIP_TOP_DIR }} -B ${{ env.TULIP_TOP_DIR }}/build

    - name: Build TULIP
      run: |
        cmake --build ${{ env.TULIP_TOP_DIR }}/build --parallel 2

    - name: Test TULIP
      run: |
        ctest --test-dir ${{ env.TULIP_TOP_DIR }}/build --output-on-failure
        
    