name: "Ubuntu | Tulip build and tests"

permissions:
  actions: write

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
    
  workflow_dispatch:

env:
  PULMTLN_TOP_DIR: pulmtln
  MFEM_TOP_DIR: mfem

jobs:
  builds-and-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [opt]
        
    name: ${{ matrix.os }}-${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout PULMTLN
      uses: actions/checkout@v3
      with:
        path: ${{ env.PULMTLN_TOP_DIR }}
        ssh-key: ${{secrets.PULMTLN_SSH_KEY}}
        submodules: 'recursive'

    - name: getcmake
      uses: lukka/get-cmake@latest

    - name: Install system packages
      run: bash ${{ env.PULMTLN_TOP_DIR }}/scripts/install-packages.sh

    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 42bb0d9e8d4cf33485afb9ee2229150f79f61a1f
        vcpkgJsonGlob: 'pulmtln/vcpkg.json'

    - name: Configure PULMTLN
      env:
        MFEM_PACKAGE: ${{ github.workspace }}/${{ env.MFEM_TOP_DIR }}/build
      run: |
        cmake --preset "gnu" -S ${{ env.PULMTLN_TOP_DIR }} -B ${{ env.PULMTLN_TOP_DIR }}/build

    - name: Build PULMTLN
      run: |
        cmake --build ${{ env.PULMTLN_TOP_DIR }}/build --parallel

    - name: Test PULMTLN
      run: |
        ctest --test-dir ${{ env.PULMTLN_TOP_DIR }}/build --output-on-failure
        
    