name: "Windows | Tulip build and tests"

permissions:
  actions: write

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
    
  workflow_dispatch:

env:
  TULIP_TOP_DIR: tulip
  MFEM_TOP_DIR: mfem

jobs:
  builds-and-tests:
    strategy:
      matrix:
        os: [windows-latest]
        target: [opt]
        
    name: ${{ matrix.os }}-${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - name: checkout TULIP
      uses: actions/checkout@v3
      with:
        path: ${{ env.TULIP_TOP_DIR }}
        ssh-key: ${{secrets.PULMTLN_SSH_KEY}}

    - name: getcmake
      uses: lukka/get-cmake@latest

    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: eed289f6e06a5e7a5c9e6a729671b0a56af7dd69
        vcpkgJsonGlob: 'tulip/vcpkg.json'

    - name: cache MFEM 
      uses: actions/cache@v3
      id: mfem-cache
      with:
        path: ${{ env.MFEM_TOP_DIR }}
        key: mfem-build-windows-opt 
      
    - name: checkout MFEM
      if: steps.mfem-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: opensemba/mfem
        path: ${{ env.MFEM_TOP_DIR }}
    
    - name: Build MFEM
      if: steps.mfem-cache.outputs.cache-hit != 'true'
      uses: mfem/github-actions/build-mfem@v2.4
      env:
        HYPRE_TOP_DIR: hypre-2.19.0
        METIS_TOP_DIR: metis-4.0.3      
        VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      with:
        os: windows-latest
        target: opt
        mpi: seq
        build-system: cmake
        hypre-dir: ${{ env.HYPRE_TOP_DIR }}
        metis-dir: ${{ env.METIS_TOP_DIR }}
        mfem-dir: ${{ env.MFEM_TOP_DIR }}
 
    - name: Configure TULIP
      env: 
        MFEM_PACKAGE: ${{ github.workspace }}/${{env.MFEM_TOP_DIR}}/build
      run: |
        cmake --preset "msbuild-vcpkg" -S tulip -B tulip/build
    
    - name: Build TULIP
      run: |
        cmake --build tulip/build/ --config Release
    
    - name: Test TULIP
      run: |
        ctest --test-dir ${{ env.TULIP_TOP_DIR }}/build --output-on-failure        
    